apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-playground

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - migrations-job.yaml
  - web.yaml
  - worker.yaml
